### ISSUE TITLE
MV and MW issue

### ISSUE THREAD

**Issue by Noobcrafteryt** [YellowPhoenix18/RealisticWorldGenerator#13]
Trying to create a world using the listed MultiVerse command with -g Realistic_World and it fails.

Changed to MW

While world is "created" loading fails.

Following is load fail for MW. Note, Creating and loading a normal world works fine.

`[16:49:20] [Server thread/INFO]: NoobcrafterYT issued server command: /mw create Survival plugin:Realistic_World[16:49:20] [Server thread/INFO]: [MultiWorld] NoobcrafterYT: Creating new world Survival. Generator: Plugin:Realistic_World. Seed: -4049702352671802127[16:49:31] [Server thread/INFO]: NoobcrafterYT issued server command: /mw load Survival[16:49:31] [Server thread/INFO]: [MultiWorld] NoobcrafterYT: Starting to load world Survival, expect some lagg![16:49:31] [Server thread/INFO]: -------- World Settings For [Survival] --------[16:49:31] [Server thread/INFO]: Mob Spawn Range: 4[16:49:31] [Server thread/INFO]: Anti X-Ray: true[16:49:31] [Server thread/INFO]: Engine Mode: 1[16:49:31] [Server thread/INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130][16:49:31] [Server thread/INFO]: Replace Blocks: [1, 5][16:49:31] [Server thread/INFO]: Nerfing mobs spawned from spawners: false[16:49:31] [Server thread/INFO]: Cactus Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Cane Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Melon Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Mushroom Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Pumpkin Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Sapling Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Wheat Growth Modifier: 100%[16:49:31] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16[16:49:31] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64[16:49:31] [Server thread/INFO]: Alternative Hopper Ticking: false[16:49:31] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1[16:49:31] [Server thread/INFO]: Random Lighting Updates: false[16:49:31] [Server thread/INFO]: Structure Info Saving: true[16:49:31] [Server thread/INFO]: Sending up to 10 chunks per packet[16:49:31] [Server thread/INFO]: Max Entity Collisions: 8[16:49:31] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617[16:49:31] [Server thread/INFO]: Max TNT Explosions: 100[16:49:31] [Server thread/INFO]: Item Despawn Rate: 6000[16:49:31] [Server thread/INFO]: Item Merge Radius: 2.5[16:49:31] [Server thread/INFO]: Arrow Despawn Rate: 1200[16:49:31] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true[16:49:31] [Server thread/INFO]: View Distance: 6[16:49:31] [Server thread/INFO]: Zombie Aggressive Towards Villager: true[16:49:31] [Server thread/INFO]: Chunks to Grow per Tick: 650[16:49:31] [Server thread/INFO]: Clear tick list: false[16:49:31] [Server thread/INFO]: Experience Merge Radius: 3.0[16:49:31] [Server thread/INFO]: Preparing start region for level 5 (Seed: -4049702352671802127)[16:49:31] [Server thread/ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MultiWorld v5.2.7 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141] at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:918) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.Bukkit.createWorld(Bukkit.java:463) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at multiworld.data.WorldManager.loadWorld(WorldManager.java:347) ~[?:?] at multiworld.data.WorldHandler.loadWorld(WorldHandler.java:129) ~[?:?] at multiworld.command.world.LoadWorldCommand.runCommand(LoadWorldCommand.java:56) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?] at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?] at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] ... 14 moreCaused by: java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections() at org.bukkit.generator.ChunkGenerator.generate(ChunkGenerator.java:76) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:99) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:918) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.Bukkit.createWorld(Bukkit.java:463) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at multiworld.data.WorldManager.loadWorld(WorldManager.java:347) ~[?:?] at multiworld.data.WorldHandler.loadWorld(WorldHandler.java:129) ~[?:?] at multiworld.command.world.LoadWorldCommand.runCommand(LoadWorldCommand.java:56) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?] at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?] at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] ... 14 more[16:49:43] [User Authenticator #2/INFO]: UUID of player SavageMiguel is b2633ea8-e3cf-4554-868f-c7d1ecbdffcb[16:49:43] [Server thread/INFO]: SavageMiguel[/98.209.86.220:52845] logged in with entity id 487 at ([Sblock] -15.5, 67.0, 246.5)[16:49:43] [pool-26-thread-1/INFO]: Creating empty config: /home/minecraft/servers/mine15847/plugins/Essentials/userdata/b2633ea8-e3cf-4554-868f-c7d1ecbdffcb.yml[16:49:54] [Server thread/INFO]: SavageMiguel issued server command: /gamemode 1[16:49:54] [Server thread/INFO]: §cSavageMiguel §4was denied access to command.[16:50:18] [Async Chat Thread - #0/INFO]: NOOB[16:50:20] [Server thread/INFO]: [MultiWorld] CONSOLE: Saved automaticly[16:50:23] [Async Chat Thread - #0/INFO]: yea?[16:50:28] [Async Chat Thread - #0/INFO]: HELLO[16:50:30] [Async Chat Thread - #0/INFO]: hi[16:50:32] [Async Chat Thread - #0/INFO]: ITS BEEN FOREVER[16:50:41] [Async Chat Thread - #0/INFO]: mhm u missed last night's streams[16:50:48] [Async Chat Thread - #0/INFO]: yeah i know[16:50:56] [Async Chat Thread - #0/INFO]: i wasnt home[16:51:02] [Server thread/INFO]: NoobcrafterYT issued server command: /mw goto Survival[16:51:02] [Server thread/ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MultiWorld v5.2.7 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141] at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:545) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at multiworld.data.PlayerHandler.movePlayer(PlayerHandler.java:76) ~[?:?] at multiworld.command.move.GotoCommand.runCommand(GotoCommand.java:82) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?] at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?] at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] ... 14 moreCaused by: java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections() at org.bukkit.generator.ChunkGenerator.generate(ChunkGenerator.java:76) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:99) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:545) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at multiworld.data.PlayerHandler.movePlayer(PlayerHandler.java:76) ~[?:?] at multiworld.command.move.GotoCommand.runCommand(GotoCommand.java:82) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?] at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?] at multiworld.command.Command.excute(Command.java:55) ~[?:?] at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?] at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] ... 14 more`

**Comment by YellowPhoenix18** [comment]
Such issues are often caused by hardware, that is to slow.

Try to make the worlds on your own pc, where you have dedicaded hardware. Many hosters are putzing to many users on an bad system. If there 100Servers on an system with 8cores, its clear, that the server wont manage that. Sadly my plugin needs massive cpu-power and this is often not given by hosting-providers.

So just do following:

1. Try the newest Version and do an test-run, if it does nor work do following:
2. Monitor your CPU with https://www.spigotmc.org/resources/serveroverview.55497/ and check, if it is extremly loaded. Maybe post the screens here.
3. Try to generate the world withan test-server on your pc. If this work, than you know, that it is an problem with your hoster

**Comment by Noobcrafteryt** [comment]
Still fails when trying to use multiverse via local test server.
Have a Core i7
Again trying 1.8
/mv create Survival NORMAL -g Realistic_World
Immediately just says failed, like on hosted server.

`[15:41:32 INFO]: NoobcrafterYT issued server command: /mv create Survival NORMAL -g Realistic_World
[15:41:32 INFO]: NoobcrafterYT: Starting creation of world 'Survival'...
[15:41:32 INFO]: [Multiverse-Core] Loading World & Settings - 'Survival' - Env: NORMAL - Type: NORMAL & generator: Realistic_World
[15:41:32 INFO]: -------- World Settings For [Survival] --------
[15:41:32 INFO]: Chunks to Grow per Tick: 650
[15:41:32 INFO]: Clear tick list: false
[15:41:32 INFO]: Experience Merge Radius: 3.0
[15:41:32 INFO]: View Distance: 10
[15:41:32 INFO]: Zombie Aggressive Towards Villager: true
[15:41:32 INFO]: Item Despawn Rate: 6000
[15:41:32 INFO]: Item Merge Radius: 2.5
[15:41:32 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:41:32 INFO]: Arrow Despawn Rate: 1200
[15:41:32 INFO]: Mob Spawn Range: 4
[15:41:32 INFO]: Anti X-Ray: true
[15:41:32 INFO]: 	Engine Mode: 1
[15:41:32 INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[15:41:32 INFO]: 	Replace Blocks: [1, 5]
[15:41:32 INFO]: Nerfing mobs spawned from spawners: false
[15:41:32 INFO]: Cactus Growth Modifier: 100%
[15:41:32 INFO]: Cane Growth Modifier: 100%
[15:41:32 INFO]: Melon Growth Modifier: 100%
[15:41:32 INFO]: Mushroom Growth Modifier: 100%
[15:41:32 INFO]: Pumpkin Growth Modifier: 100%
[15:41:32 INFO]: Sapling Growth Modifier: 100%
[15:41:32 INFO]: Wheat Growth Modifier: 100%
[15:41:32 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[15:41:32 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:41:32 INFO]: Alternative Hopper Ticking: false
[15:41:32 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[15:41:32 INFO]: Random Lighting Updates: false
[15:41:32 INFO]: Structure Info Saving: true
[15:41:32 INFO]: Sending up to 10 chunks per packet
[15:41:32 INFO]: Max Entity Collisions: 8
[15:41:32 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[15:41:32 INFO]: Max TNT Explosions: 100
[15:41:32 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:41:32 INFO]: Preparing start region for level 5 (Seed: -4002121350889383255)
[15:41:32 WARN]: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[15:41:32 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:920)
[15:41:32 WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[15:41:32 WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[15:41:32 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[15:41:32 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[15:41:32 WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[15:41:32 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[15:41:32 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[15:41:32 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[15:41:32 WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
[15:41:32 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:41:32 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:41:32 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[15:41:32 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:41:32 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[15:41:32 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:41:32 WARN]: Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections()
[15:41:32 WARN]: 	at org.bukkit.generator.ChunkGenerator.generate(ChunkGenerator.java:76)
[15:41:32 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:99)
[15:41:32 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140)
[15:41:32 WARN]: 	... 27 more
[15:41:32 ERROR]: [Multiverse-Core] The world 'Survival' could NOT be loaded because it contains errors and is probably corrupt!
[15:41:32 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'Survival'
[15:41:32 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[15:41:32 ERROR]: [Multiverse-Core] Failed to Create/Load the world 'Survival'
[15:41:32 INFO]: NoobcrafterYT: FAILED.

`

Caused by: java.lang.UnsupportedOperationException: Custom generator is missing required methods: generate(), generateBlockSections() and generateExtBlockSections()

Could be problem?

**Comment by YellowPhoenix18** [comment]
Are you sure youre using Spigot? For me it seems to be craftbukkit. Craftbukkit has some good Generating-Methods missing. For best pratice, test https://yellowphoenix18.de/downloads/spigot.jar . This jar should work for 1.8-Servers and is the version Iam coding with

**Comment by Noobcrafteryt** [comment]
Yep it's Spigot, which is built off craftbukkit.

**Comment by Noobcrafteryt** [comment]
used's spigots method of buildtools --rev 1.8

**Comment by YellowPhoenix18** [comment]
okey. Please try that version Ill send you. On my test-server I had never problems with that generating-methods missing.

**Comment by Noobcrafteryt** [comment]
ok

**Comment by YellowPhoenix18** [comment]
Still the problem?

**Comment by Noobcrafteryt** [comment]
You said you were going to send me a version. I've been waiting on that.

Did you just update latest version on Spigot?

I try on my computer with the version I have and still no luck. My computer has more than enough CPU power to run the plugin.

Talked to hosting provider and they said the same.
